server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customers-orders-coupons?currentSchema=client_manager
    username: denis
    password: gfhjkm
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format_sql: true
#      mappingclass: dev.sorokin.entity.Client